vn.say(None, "Buddha jesus khrisna allah yahweh satan lucifer give me strength...")
vn.say("Karen", "FOR DAYS I LEFT THIS BREAD IN-")
vn.say("Nyarla", "Ahem...")
vn.say(None, "A soft but authoritative voice appeared next to me. He sound different now, a bit more calmer? Guess he can be serious for once...")
vn.say("Nyarla", "I'm the manager, you said you were looking for me?")
vn.say("Karen", "Yes! It's about the quality of the product sold in your-")
vn.say("Nyarla", "Gas Station convenience store yes...")
vn.say(None, "The manager's smile didn't waver as he stepped closer to the woman.")
vn.say("Nyarla", "Let's talk somewhere else more comfortable, there's a room upstairs.")
vn.say(None, "I watched as the manager led the woman upstairs")
vn.say(None, "Wait... Wait, what the hell? Since when is there a second floor? Since when is that marble staircase here? Wait...")
vn.say(None, "I couldn't hear anything for a moment there, and when I tried to walk up to the staircase, an invisible... something stopped me on my tracks.")
vn.say(None, "He's definitely eldritch...")
vn.say(None, "After waiting for a while the two returned.")
vn.say(None, "The elven woman is no longer scowling. In fact she's beaming, as if her outburst never really happened in the first place.")
vn.say("Karen", "to the nexus point!")
vn.say("Nyarla", "Indeed! Now you get it!")
vn.say("Karen", "Oh gosh, you... Uhhh...")
vn.say(None, "The woman  walked up towards me and squinted at my nametag. I took a step back, just a tiny bit confused / startled.")
vn.say("Karen", "Miss Rue! I'm so, so sorry about my outburst...")
vn.say(None, "Somehow, I'm still not satisfied...")
vn.say("Rue", "yeah it's fine, used to it, would you like your bread back?")
vn.say("Karen", "Oh definitely! Thank you! I'll definitely return here if I have a chance.")
vn.say(None, "I watched as the woman left...")
vn.say("Nyarla", "Is that what you want?")
vn.say("Rue", "What?")
vn.say("Nyarla", "You apologized, so I assume you wanted her to respond in kind. If that's not what you want, well, you can try again.")
vn.say("Rue", "huh?")
vn.say(None, "The manager smiled.")
vn.say("Nyarla", "I have other things to take care of, give me a holler if you need anything, see ya~")
