vn.say("Karen", "FOR DAYS I LEFT THIS BREAD ON THE COUNTER AND YET!")
vn.say(None, "What was that quote again? The one from the ballad about some greek hero?")
vn.say(None, "Ruthlessness Was Mercy Upon Ourselves... Right, that one...")
vn.say(None, "Time to show myself mercy then...")
vn.say("Karen", "And for this I dema-")
vn.say(None, "The Karen's words were cut short. A drop of blood drip down her neck. My hand was inches away from hers, dagger-like nail scraped a soft skin.")
vn.say(None, "I found my entire body paralyzed. Numerous tentacles coiled around my arm, stopping me in cable-like grip. No matter how much I try the Tentacle didn't budge an inch.")
vn.say("Nyarla", "Whoa hey, Rue, come on now, don't kill the customer it's bad for business!")
vn.say("Karen", "You... YOU DISEASED MANIAC!")
vn.say(None, "The Karen turned wildly towards Nyarla.")
vn.say("Karen", "And you! You're the manager aren't you?! How can you let this... MONSTER-")
vn.say("Aster", "Let's take this somewhere more comfortable. Come on, I have a room in the back.")
vn.say(None, "I watched as the manager led her to a staircase that led downstairs. The stairs are dark polished obsidian and even though I can see perfect in the dark, I can't really make out the bottom.")
vn.say(None, "...")
vn.say(None, "Now that I think about it, I don't remember there's ever any stairs in this store.")
vn.say(None, "After a while, the manager returns with the woman. I'm not sure what happened but there's this haunted look on her face.")
vn.say(None, "The woman who stepped out is an entirely different person. Her gaze look around in fear, she trembles, her body language a mess, and she stumbled in her steps.")
vn.say("Nyarla", "Well now, is there anything else?")
vn.say("Karen", "N-no! No! I'm sorry please forgive this one, please no more, no more, please, I was wrong I'll do anything let me go, please, please just....")
vn.say("Nyarla", "Alright you are free to leave~")
vn.say(None, "I watched as the woman bolted out the store, stumbled and fell hard on the pavement before running away again.")
vn.say(None, "Then a truck came barreling in and hit her.")
vn.say(None, "...")
vn.say(None, "She's dead now.")
vn.say("Nyarla", "Oooh, rest in peace...")
vn.say(None, "I blinked.")
vn.say("Rue", "What did you do?")
vn.say("Nyarla", "Torture, magic torture, make it feel like she suffer for years in the span of minutes.")
vn.say("Rue", "Seriously?")
vn.say("Nyarla", "That's what you wanted no? You tried to kill her, you hate her, you want something bad to happen to her.")
vn.say(None, "The manager pointed a tentacle at the cctv camera.")
vn.say("Nyarla", "But we can't really do that where forensic angel unit can make investigation, so...")
vn.say("Rue", "Right... okay...")
vn.say("Nyarla", "Anyway, I got work to do, give me a holler if you need anything!")
