vn.say("Karen", "FOR DAYS I LEFT THIS BREAD IN")
vn.say("Rue", "Manager!")
vn.say(None, "The squid person pops up behind me.")
vn.say("Nyarla", "You rang? Oh! Hello, how can I help you?")
vn.say("Karen", "Are you the manager?")
vn.say("Nyarla", "At your service~")
vn.say("Karen", "Well, listen, I just put this "bread" on the counter and LOOK AT IT")
vn.say(None, "The perfectly normal slice of bread lay on the counter. The manager touched it with his finger.")
vn.say("Nyarla", "It's a bit dry...")
vn.say("Karen", "No! It's not moldy! There's no sign of mold or rot, it's like nature itself refuses to claim this bread!")
vn.say("Nyarla", "You know humidity plays a role in-")
vn.say("Karen", "I WANT MY MONEY BACK AND DEMAND A PROPER COMPENSATION!")
vn.say(None, "The manager blinked, though his laid back grin never disappear")
vn.say("Nyarla", "Okay, okay... Let's talk more, I have a room in the back.")
vn.say(None, "You watched as the manager led the woman to the door in the back. The one that led to the office at...")
vn.say(None, "Wait no, that's the other door? Wait, huh? Since when are there two doors here? Wait huh?")
vn.say(None, "I watched as the two disappeared into the door. A strange mahogany door that looked out of place in this convenience store. I tried opening the door, but it's locked shut.")
vn.say(None, "After a while the door opened and the manager stepped out, the woman nowhere to be seen.")
vn.say("Rue", "Wait where is she?")
vn.say("Nyarla", "Where is who?")
vn.say("Rue", "The woman? The elf?")
vn.say("Nyarla", "Hmm? Could've sworn she was an arachnid.")
vn.say(None, "You blinked and looked back at the doors.")
vn.say(None, "But... The mahogany door is nowhere to be seen.")
vn.say(None, "A grin suddenly formed on Nyarla's face.")
vn.say("Nyarla", "I'm just messin' with ya!")
vn.say(None, "A tentacle pat your back.")
vn.say("Nyarla", "Don't worry the karen is handled, you don't have to worry about her anymore.")
vn.say("Rue", "What do you mean handled her?")
vn.say("Nyarla", "Hmm? Why do you suddenly care so much about her? You asked me to handle her, it's too late to change your mind~")
vn.say("Rue", "Uhh... Wait...")
vn.say("Nyarla", "I got stuff to do, see ya, give me a holler if you need anything.")
