vn.say(None, "Well, such is the cruel and uncaring world. Why should I involve myself?")
vn.say(None, "I continue looking at the red light, waiting for it to go green.")
vn.say(None, "???: Catch that brat!")
vn.say(None, "I shook my head, ignoring the screams, when the world suddenly tilted.")
vn.say(None, "A human girl, a human man, a troll, and a wolf kin crashed on to my bike sending us all tumbling on the the asphalt.")
vn.say(None, "I scrambled on to my feet to check on the bike. There were scratches all over and the rearview mirror is broken.")
vn.say(None, "I glared at the offending group, a blood red sword materialized in your grip.")
vn.say(None, "The three trouble maker's face turned ashen, but the girl.. The girl just gazed at me with wide eyes.")
vn.say(None, "I watched as the other three fled into the night, leaving you with just the girl.")
vn.say("Girl", "Th-thank you! Umm... My name's Mia and...")
vn.say(None, "I tried turning on your bike, it whines pathetically.")
vn.say("Rue", "Mia huh... What are you up to at this godless hour?")
vn.say("Mia", "W-well.... I was in the library, I fell asleep in the outdoor reading area and... It's night. And my phone battery died...")
vn.say("Rue", "Right...")
vn.say(None, "I continue trying to start your bike and it's finally rumbling.")
vn.say("Rue", "Finally...")
vn.say(None, "I hopped on to the bike and I can feel Mia hopped on to the seat behind me.")
vn.say(None, "I don't remember inviting this brat.")
vn.say("Mia", "Oh, right, umm... You can drop me off on the nearest bus stop, I can manage, it's okay!")
vn.say(None, "There are no bus at this hour, she'll have to wait two more hours before anything can pick her up.")
vn.say(None, "Should I help her? She smells like trouble, and I don't give a shit about her..")
vn.say("Rue", "Fine... I'll give you a ride home kid, where do you live?")
vn.say("Mia", "Oh! Umm, thank you! It's, it's not far from here I swear!")
vn.say(None, "I rolled my eyes and ride down the road with the human girl sitting behind me. She clutched on to me carefully, as if afraid of offending me even more.")
vn.say("Mia", "So ummm... What's your name?")
vn.say(None, "Her voice was a little muffled behind my back. I can barely make it out.")
vn.say("Rue", "Rue")
vn.say("Mia", "Rue! Okay, okay... Oh, turn right here!")
vn.say(None, "After a while, I finally made it to a small house at the outskirts of the city. There's a silhouette of a massive mansion nearby.")
vn.say(None, "Mia hopped off and walked up to the small house. She knocked on it.")
vn.say(None, "???: Nyandayo...")
vn.say(None, "???: Mia, it's 4 am in the morning what are you...")
vn.say(None, "The person who stepped out is a young man, hair pulled in a pony tail, and a pair of cat-like ears on his head.")
vn.say("Mia", "Mikalio nii san!")
vn.say(None, "The girl lunged at Mikalio, hugging him.")
vn.say("Mikalio", "The hell?")
vn.say(None, "The man looked at me.")
vn.say("Mikalio", "Who are you? Did she rope you into...")
vn.say("Mia", "Ah! We should head inside it's super late! Thanks a lot Rue!")
vn.say("Mikalio", "Wait... Mia what the hell, hey don't just walk into my...")
vn.say(None, "The door closed shut before I could say another word.")
vn.say(None, "Strange girl... And something tells me this isn't really her home...")
