vn.say(None, "I parked my bike near the sidewalk and walked up towards them. Let's do a classic 'I know this person'")
vn.say("Rue", "Hey, I'm looking for someone ordering a ride...")
vn.say(None, "???: That's me! Mia! Mia Scarlet?")
vn.say(None, "The girl shouted and ran up to mee, before hiding behind me.")
vn.say(None, "I looked at the group.")
vn.say("Rue", "You got a problem?")
vn.say("Troll", "Ugh, killjoy, piss off corpse breath")
vn.say(None, "I flipped them off as they walked away.")
vn.say(None, "Then I turned to the girl.")
vn.say("Rue", "Friend of yours?")
vn.say("Mia", "Y-yes... They're I mean NO! God no, I was just around...")
vn.say("Rue", "What are you doing at this godless hour? Need a hitch a ride back home?")
vn.say("Mia", "Uhh, ummm, yes... I mean, I was just, I... I fell asleep in there and now its...")
vn.say(None, "The girl gestured at a nearby building. It's a library, with a nice park bench in front of it. Places where people read, usually when the sun is up.")
vn.say("Mia", "But my phone battery died and I can't call a-")
vn.say("Rue", "Alright, alright, geez... Hop on, where do you live?")
vn.say("Mia", "Oh, thank you! It's umm.. Just go down this road...")
vn.say(None, "I can feel Mia hopping on to the bike behind me and I started the engine once again.")
vn.say(None, "I ride down the road with the small human girl clinging on to me like a lifeline. I could've sworn I've seen her somewhere but I can't seem to remember.")
vn.say("Mia", "So ummm... What's your name?")
vn.say(None, "Her voice was a little muffled behind my back. I can barely make it out.")
vn.say("Rue", "Rue")
vn.say("Mia", "Rue! Okay, okay... Oh, turn right here!")
vn.say(None, "After a while, I finally made it to a small house at the outskirts of the city. There's a silhouette of a massive mansion nearby.")
vn.say(None, "Mia hopped off my bike and walked up to the small house. She knocked on it.")
vn.say(None, "???: Nyandayo...")
vn.say(None, "???: Mia, it's 4 am in the morning what are you...")
vn.say(None, "The person who stepped out is a young man, hair pulled in a pony tail, and a pair of cat-like ears on his head.")
vn.say("Mia", "Mikalio nii san!")
vn.say(None, "The girl lunged at Mikalio, hugging him.")
vn.say("Mikalio", "The hell?")
vn.say(None, "The man looked at me.")
vn.say("Mikalio", "Who are you? Did she rope you into...")
vn.say("Mia", "Ah! We should head inside it's super late! Thanks a lot Rue!")
vn.say("Mikalio", "Chotto... Mia what the hell, hey don't just walk into my...")
vn.say(None, "The door closed shut before I could say another word.")
vn.say(None, "Strange girl... And something tells me this isn't really her home...")
