vn.say(None, "After a long day of work, it's finally 4 AM and i can finally clock out. The sun isn't up yet, but fuck me I'm already tired. Not that the sun bothers me, it's just annoying. The whole spiel about Vampires burning in daylight doesn't apply much anymore after the Vampire Billionaire Diva, Merilia Azure revolutionize the Sunscreen Industry.")
vn.say("Nyarla", "Alright, thanks for today Rue!")
vn.say("Rue", "Do you clock out manager?")
vn.say("Nyarla", "Hm? Oh no, I live here, anyway, not bad for first day, here...")
vn.say(None, "A tentacle handed me a wad of cash.")
vn.say("Rue", "What's this?")
vn.say("Nyarla", "A first day package, it's not part of your salary, but like... Since you won't be paid until the end of this month, I figure you'll need something to get by on your first month~")
vn.say("Rue", "Oh, uhh... thanks...")
vn.say(None, "I walked down the dark streets outside of the gas station. I can see some cars parked around, there's always more cars than the amount of people that is actually here. Not to mention the gas station itself.")
vn.say(None, "There's the traditional gas station, the electric charging station, but there's also... a stable? A large box with fresh wheat in it?")
vn.say(None, "I decided not to question anything and walked on to my motorbike.")
vn.say(None, "An old model, but one of the best in its prime. The rev of the engine doesn't send a thrill, it sends comfort, a rumbling purr that's just... ah fuck me, I'm finally home.")
vn.say("Rue", "Well then, time to go back...")
vn.say(None, "I rode down the city on my motorbike. The city skyline of Avarath looms ahead of you. The glistening lights, the massive dragons carrying billboards and advertisements. Magic swam in the air showing off ads of heaven, hell, and everything in between.")
vn.say(None, "Oh fuck red light. I squeezed and stop the bike. Just barely as a flash of  traffic light snaps a photo at me. I flipped it off, knowing full well that I won't even appear on the camera.")
vn.say(None, "It was then that I heard something.")
vn.say(None, "???: Get off me!")
vn.say(None, "I turned my head to a nearby alleyway. I see it then, a young girl, surrounded by rough looking people. A few demi human and a human. Well, don't matter their race is, they're harassing this girl now.")
vn.say(None, "I watched as a troll-like (or actual troll) surrounded the girl. His friends laughed cruelly.")
vn.say(None, "4 AM is basically dead hour anyway... They don't expect anyone especially not the angels to show up at this time of day.")
vn.say(None, "I decided to handle this...")
vn.say(None, "A. Gracefully")
vn.say(None, "B. Handle? No, this is not my problem")
vn.say(None, "C. Very Violently")
