vn.say(None, "Ahh... Let's see...")
vn.say(None, "Personally, I don't give a shit about saving a damsel in distress. But fuck me, I need to destress and well...")
vn.say(None, "I parked my bike near the side walk and stepped out. A blood red sword materialized in my grip. I don't show up on CCTV anyway, so...")
vn.say(None, "Yeah...")
vn.say("Rue", "Hey...")
vn.say(None, "The group turned towards us.")
vn.say("Troll", "Ha? What's this bitch doing...")
vn.say("Wolf", "Wait, wait, that looks like.")
vn.say("Human", "VAMPIRE!!!")
vn.say(None, "Ah, they changed their tune fast once they know what I am...")
vn.say(None, "I blitzed in front of the troll who already let go of the girl.")
vn.say("Rue", "Nothing personal...")
vn.say(None, "I stabbed his ankle, sending him to his knee.")
vn.say("Troll", "Gwaaaah! You bit-")
vn.say(None, "I use my left hand to grab his massive shoulder, then just squeezed, hard, twisting it. I can feel him struggling, screaming at the heavens until finally.")
vn.say(None, "'CRACK'")
vn.say(None, "Blood and gore sprayed as I wrenched out his arm like fucking lego. Then I turned to all the others who started running.")
vn.say(None, "I grabbed the screaming ogre by the head, a fountain of blood burst forth, and throw the head like a projectile towards the fleeing Wolf-man. The head hits his back with a crack, sending him tumbling forward, paralyzed.")
vn.say(None, "Then I blitzed in front of the human.")
vn.say("Human", "No, no, no, mercy, mercy, please!")
vn.say(None, "I grabbed his finger then snapped it, one by one. He tried to run away, but I kicked his shin, crippling him. Then I spend some time snapping his fingers one by one, enjoying his screams as he begged for death.")
vn.say(None, "After a while his voice become too hoarse and stabbed him in non-vital organ so that he'll bleed out.")
vn.say(None, "Then finally I walked up towards the wolf man lying next to the head. His eyes are full of fear, his body paralyzed. I grabbed him by the neck, hung him to the wall with one hand and start skinning him alive with another.")
vn.say(None, "After a while, he died of blood loss and I tossed their corpses in a pile.")
vn.say(None, "...")
vn.say(None, "Oh fuck that's totally illegal...")
vn.say(None, "I face palmed.")
vn.say("Rue", "Ugh... Rue, you goddamn, fucking idiot...")
vn.say(None, "I turned to the girl that I 'saved' finding  her...")
vn.say(None, "Still there, not screaming, not crying, just... stare at me with wide eyes...")
vn.say(None, "And her hand on her crotch, which she quickly pulled up the moment my gaze  landed on her.")
vn.say("Mia", "Ngh, oh oh ah.. um. uhh... Th-thank you for saving me... You uhh, I...")
vn.say("Rue", "Sorry for the mess kid...")
vn.say("Mia", "IT'S FINE!!! I mean, I mean...Umm.. we should get out of here before the angels showed up???")
vn.say("Rue", "We?")
vn.say("Mia", "Ah, I mean, umm, my home is a bit far away from here and I... I kinda... hope you'd be willing to give me a ride home...")
vn.say(None, "I looked down on my blood soaked clothes and body then back at Mia.")
vn.say("Rue", "You sure about that?")
vn.say("Mia", "YES! I mean, I mean, umm... I don't mind!!!")
vn.say("Rue", "Alright, hop on...")
vn.say(None, "I hopped on to my trusty bike and she sat right behind me, breathing heavily.")
vn.say(None, "The night city air helped with drying up the blood all over me, just barely. I can feel Mia clinging on to me, pressing her face against  me despite I'm covered in blood.")
vn.say("Mia", "S-so... what's your name?")
vn.say("Rue", "Rue")
vn.say("Mia", "Ah, umm... My name is Mia... nice to meet you...")
vn.say("Rue", "Mia huh...")
vn.say("Mia", "Oh, right turn over there... Near that spooky mansion...")
vn.say(None, "The girl led me to a simple house near a large mansion. She hopped off the bike and knocked on the door.")
vn.say(None, "???: Nyandayo...")
vn.say(None, "The door  opened, revealing a boy with a pony tail and a pair of cat-like ears. He glanced at me, then at Mia, then sighed.")
vn.say("Mia", "Mikalio nii-chan!")
vn.say("Mikalio", "No")
vn.say(None, "The boy closed the door shut in front of us.")
vn.say("Mia", "Ah wait, please! Let me stay here for... I mean, don't ground me! These are just... Ketchup! yes! Not real blood!!!")
vn.say(None, "Mia banged on the door.")
vn.say("Mia", "I'll pay you triple!!!")
vn.say(None, "The door opened and Mikalio steps out.")
vn.say("Mikalio", "For real?")
vn.say("Mia", "YES!")
vn.say(None, "Mikalio turned to me then back to Mia.")
vn.say("Mikalio", "Thank you for... Helping my... What are you supposed to be again?")
vn.say("Mia", "Sister!")
vn.say("Mikalio", "Right, my 'sister', fuckin' hell, just... just get in you brat...")
vn.say(None, "I watched as the two entered the house, leaving me alone, blood drenched.")
