vn.say(None, "I took a quick shower the moment I get home.")
vn.say(None, "Just rinse off the filth off me, put on whatever, and just lay flat on the bed.")
vn.say(None, "I gazed at the ceiling, this shoebox apartment that I've called home for 10 years now...")
vn.say(None, "Aren't vampires supposed to live in big mansions?")
vn.say("Rue", "Haa...")
vn.say(None, "And it's so hot and humid...")
vn.say(None, "Look, I don't give a shit, I don't want much in life. But...")
vn.say(None, "I really, really want to get out of this country. Somewhere darker, colder.")
vn.say(None, "It's too hot and humid in this dumpster fire.")
vn.say("Rue", "100.000 blips")
vn.say(None, "That's how much I need to save up to get out of here. It's... not much at all.")
vn.say(None, "My salary at Pandora is 7000 blips monthly, that's 84.000 blips in 12 months if I don't eat or use it for anything.")
vn.say(None, "Minus rent and utilities, I'll save up after 2  years of work. I just can't eat or buy gas.")
vn.say("Rue", "Not that I need to eat...")
vn.say(None, "I closed my eyes as the sun finally rose.")
