vn.say(None, "I sighed, feeling really out of place in this uniform.")
vn.say(None, "The Pandoramart, the Hope at the End of the Gas Station. God, it's cringe, it's so cringe I can feel the cringe. And I'm not suppose to be able to feel anything.")
vn.say("Nyarla", "Alright Rue! First Day at the job, are you excited?")
vn.say(None, "My manager is a... He call himself squid person. With all the tentacles and bubbly laid back personality.")
vn.say(None, "But I wasn't born yesterday, I know an eldritch when I see one.")
vn.say("Rue", "Uhhh... Yeah?")
vn.say("Nyarla", "Great! Now then here's how you use your convenience store stuff...")
vn.say("Rue", "Convenience store stuff? Do you actually know how any of this works?")
vn.say(None, "The manager pouted, like actually pouted.")
vn.say("Nyarla", "Myoooo~ What kind of question is that? Ahem, anyway, the most important thing is to be nice to customer.")
vn.say("Rue", "Like, polite?")
vn.say("Nyarla", "You're a natural!")
vn.say("Rue", "So.. That's it? I walk in and suddenly I'm on payroll?")
vn.say("Nyarla", "Oh right the uhhh... The thing, the...")
vn.say("Rue", "Job Interview")
vn.say("Nyarla", "Exactly! That! Ahem, anyway...")
vn.say(None, "A tentacle suddenly appear carrying clipboard and paper.")
vn.say("Nyarla", "So tell me about yourself")
vn.say(None, "*flashbacks*")
vn.say("Rue", "I was a Blood Slave Unit in the 4th Rapture.")
vn.say("Nyarla", "Oh, Rapture, yes, yes, that brings back memories. When was that again? Last week?")
vn.say("Rue", "400 years ago... Look, sir, drop the act you're not fooling anyone.")
vn.say(None, "The squid in front of me flinched as if struck.")
vn.say("Nyarla", "What? No! I'm not... Ahem, let's focus on you instead of my background. Any criminal background I should know of?")
vn.say("Rue", "Well, I killed, a lot")
vn.say("Nyarla", "Ah yes, murder, but it's war, so nothing wrong with that. You're all green, you passed the interview!")
vn.say(None, "I blinked, slowly is this... Thing for real?")
vn.say("Rue", "I chucked a baby out of window")
vn.say("Nyarla", "You what?")
vn.say("Rue", "I killed an entire family, then throw the baby out of a five stories window and never looked back.")
vn.say("Nyarla", "Well this is a long time ago so...")
vn.say("Rue", "20 years ago")
vn.say(None, "The squid paused, contemplating it.")
vn.say("Nyarla", "In a sense, you did the baby a favor.")
vn.say(None, "What?")
vn.say("Nyarla", "Nyahaha~ think about it, the baby had no sin right? If you let the baby live they might grow up and do sin and go to hell.")
vn.say("Rue", "What the fuck...")
vn.say(None, "The man wiggled a finger in front of me.")
vn.say("Nyarla", "But since you offed the baby, it gets a guaranteed ticket to heaven! Maybe even with their family that your killed! In a sense you have spared the baby from eternal damnation and granted the baby eternal bliss of heaven.")
vn.say(None, "That... That's... hmmm...")
vn.say("Nyarla", "Anyway, let's get to the floor, your shift is starting.")
vn.say(None, "*starting card, music, etc*")
vn.say("Nyarla", "Welcome to Pandoramart! The hope at the end of the gas station!")
vn.say(None, "The customer barely noticed the friendly squid person waving their hands and tentacles, and simply skittered down the aisle looking for something.")
vn.say("Nyarla", "Alright Rue, now you try.")
vn.say("Rue", "Why? Why are we greeting them?")
vn.say("Nyarla", "To make them feel welcomed!")
vn.say("Rue", "They don't give a shit...")
vn.say("Nyarla", "Aww, come on... Just try! Pretty please? Just wanna trying to lighten things up before I put you on the payroll.")
vn.say(None, "The squid manager retreated behind the counter and start fiddling with his phone, his other tentacles busy restocking the shelves behind me.")
vn.say("Customer", "I'll have these...")
vn.say(None, "A soft voice called my attention, it's an arachne, she's wearing a simple school uniform, her many eyes blinked at me, framed with white hair.")
vn.say(None, "I scanned a toothbrush, some grub crispies, and one of of those playing card thing.")
vn.say("Rue", "That'll be 470 blips, cash or credit?")
vn.say(None, "The customer fished out her phone.")
vn.say("Customer", "Do you support E-Wallet?")
vn.say(None, "I grabbed the edc machine and completed the transaction.")
vn.say("Customer", "Thank you")
vn.say("Rue", "You're Welcome")
vn.say(None, "As the customer skittered out, the door slammed open. An elf stepped in, looking pissed. Angry. And impatient.")
vn.say("Rue", "Welcome to Pandoramart how may I-")
vn.say(None, "A piece of bread landed on my face. It's dry and it flopped on to the counter after gravity took over.")
vn.say("Karen", "You sold me this disgusting abomination of all things pure and sacred!")
vn.say(None, "I grabbed the bread and gazed down at it. Contemplating first degree murder.")
vn.say("Rue", "The bread?")
vn.say("Karen", "THAT is not a bread.... That thing was grown in a box, sprayed with chemicals, ground up and liquified in poison, and painted white to make it look like bread!")
vn.say(None, "I wonder if there's any difference between human and elf once I tear their ears apart...")
vn.say("Rue", "Ma'am...")
vn.say("Karen", "GOD HAD NO HAND IN THE CREATION OF THIS ABHORRENCE! THE FACT THAT THIS DISGUSTING-")
vn.say("Choice A", "Apologize")
vn.say("Choice B", "Call the manager")
vn.say("Choice C", "Send Her To Meet God")
