vn.say("Rue", "I don't hate you")
vn.say(None, "Mia's eyes widened, her lips  parted as she gazed up at me.")
vn.say("Mia", "You don't? But... you keep...")
vn.say("Rue", "I was on my shift, you're bothering me during my work.")
vn.say(None, "A blush formed on her face.")
vn.say("Mia", "Y-you mean...")
vn.say("Rue", "Yes, next time, come visit me after I clock out.")
vn.say(None, "The girl looked down and clenched her fist.")
vn.say("Mia", "Y-you... You didn't tell me! I thought, I thought you hate me and you keep pushing me away and... And I know I'm being creepy, but, but , but I was so, so scared that you hate me and...")
vn.say(None, "I put a hand over her head, gently patting it.")
vn.say("Rue", "No, you're annoying brat, yes, but I don't hate you")
vn.say(None, "Mia's lips quivered and she folded her arms.")
vn.say("Mia", "W-well, I hate you now! For, for playing with my poor maiden heart!!!")
vn.say("Rue", "That's a shame")
vn.say(None, "I stood up and head for my bike.")
vn.say("Mia", "WAIT WAIT WAIT I WAS JUST JOKING!!!")
vn.say(None, "The girl grabbed my hand, clutching it hard.")
vn.say("Rue", "You're giving me mixed messages")
vn.say("Mia", "YOU'RE MIXED MESSAGES!!!!")
vn.say(None, "I sighed and turned back to Mia.")
vn.say("Rue", "What do you want?")
vn.say("Mia", "I... I want a friend and... mansion, do you... do you wanna come? Visit me?")
vn.say(None, "I sighed.")
vn.say("Rue", "I don't have a mansion to give you")
vn.say("Mia", "THAT'S NOT- Don't... Ahhh, you're teasing me! You know what I meant!!!")
vn.say(None, "I smirked a little")
vn.say("Rue", "Then, what do you mean?")
vn.say("Mia", "I just like... I just want a cool friend like you and...")
vn.say(None, "I shrugged and turned to the direction of the big mansion.")
vn.say("Rue", "You need a ride home then?")
vn.say(None, "The girl beamed.")
vn.say("Mia", "Oh my gosh yes!!!")
