vn.say("Rue", "Yes, I want to hurt you")
vn.say(None, "Mia froze and looked up at me with wide eyes.")
vn.say("Rue", "I want to tear you apart and hear you scream. I want to hear you beg for god to save you. I want to break you until there's nothing left.")
vn.say(None, "I stood up, turned towards her, and grabbed her throat.")
vn.say("Rue", "It's fucking illegal, yknow?? Murder? Hurting?")
vn.say(None, "I squeezed and a keening gasp slid out of her throat, but I didn't let go.")
vn.say("Rue", "It's unfair, a monster like me, forced to live like some civilized people...")
vn.say(None, "I tossed her to the pavement.")
vn.say("Mia", "Guh! Haa! Haaa... Haa...")
vn.say(None, "The girl gasped for breath, holding her throat.")
vn.say(None, "I kicked her casually making her whimper.")
vn.say("Rue", "And then you came along... A fucking human... With all your clinginess, persistence...")
vn.say(None, "I crouched down in front of her.")
vn.say("Rue", "I feel like a caged animal in a zoo, starving... And there's you, a little girl, jeering and pointing from behind the glass...")
vn.say("Mia", "I-I'm so-AAAAAAAH!!!")
vn.say(None, "I stomped on her leg crushing it.")
vn.say("Mia", "Aaaaaah!  Haaaa! Don't I... I need to...")
vn.say("Rue", "Thought you're into this???")
vn.say(None, "I kicked her like a ragdoll, sending her and blood all over the parking lot.")
vn.say("Rue", "Talk to me again, and I will kill you")
vn.say(None, "Mia coughed and scrambled a little, taking a look at her leg.")
vn.say("Mia", "W-wait... I.. I need this...")
vn.say("Rue", "What?")
vn.say("Mia", "My legs, just... just in case... just in case I have to... chase after you again...")
vn.say("Rue", "Why? So you I can break you again?")
vn.say("Mia", "N-no, I mean, yes, I mean... Do you, do you hate me less now...?")
vn.say("Rue", "Maybe")
vn.say("Mia", "Then... then... come visit me? You can... hurt me, anytime you like, like this... Just... promise you visit me... a lot...")
vn.say(None, "I rolled my eyes.")
vn.say("Rue", "Fine...")
vn.say(None, "A weak smile appeared on Mia's face.")
vn.say("Mia", "Thank you... Ahh... I need to... get back though...")
vn.say(None, "I looked at her shattered leg then walked up to my bike.")
vn.say("Rue", "Hop on, I'll take you to the nearest hospital")
vn.say("Mia", "I prefer healer in temple... Doctors are scary")
vn.say("Rue", "I will break your other leg if you consider that again...")
vn.say("Mia", "O-okay... okay... Doctor then...")
