vn.say("Rue", "Nothing, I want you gone")
vn.say(None, "Mia said nothing at first she just gazed at me, unreadable expression on her face.")
vn.say(None, "Then she looked down a full body shudder shook her body.")
vn.say("Mia", "Y-yeah... but...")
vn.say(None, "The girl clenched her fist.")
vn.say("Mia", "What if... I change for you? What if... What if I'm not Mia, would you still hate me?")
vn.say("Rue", "No, because I don't like humans, or people in general. Please get out of my life.")
vn.say("Mia", "Don't say that.. Please...")
vn.say("Rue", "Or kill yourself, but don't involve me")
vn.say(None, "The girl's breath hitched and I sighed in slight frustration.")
vn.say("Rue", "Is there anything I can say so that I don't have to see you again?")
vn.say(None, "Mia shook her head.")
vn.say("Rue", "You're just gonna keep chasing after me? Why?")
vn.say("Mia", "You can kill me... Then I won't bother you anymore...")
vn.say(None, "The girl looked up at me again.")
vn.say("Mia", "I don't like living, it hurts, being alive hurts, I... I'm not joking, I want to die and now the reason I'm alive....")
vn.say(None, "Mia shuddered her voice cracking")
vn.say("Mia", "I... I can't live with this, please... Just... please... give me a chance.")
vn.say("Rue", "No")
vn.say(None, "I stood up.")
vn.say("Mia", "Just one more week!!!")
vn.say(None, "The girl gripped my arm, clutching it tight.")
vn.say("Mia", "Spend... spend time,  with me, for one week in the mansion... Visit, just an hour everyday, and I promise you, I'll kill myself, you can have my mansion, you can... you can do whatever you want to my body. Then that's it. I will be gone from your life, you won't see me, ever again...")
vn.say(None, "I paused and turned to her. Hmm... If she keep her promise, I can focus on my job after one week.")
vn.say("Rue", "If you chicken out at the end of the week, I will kill you myself, got it?")
vn.say("Mia", "Y-yes! Thank you... Thank you!")
