vn.say(None, "It's finally weekend.")
vn.say(None, "I decided to keep my promise, I'm not a monster. I stood by my words.")
vn.say(None, "(Also because us vampires can be bound by promise, but Mia must *never* know that)")
vn.say("Rue", "Hmm...")
vn.say(None, "I stood in front of the mansion, I tried entering, I tried pressing my hand against the gate.")
vn.say(None, "Some invisible barrier stopped me from even touching the gate.")
vn.say(None, "Right, I can't go into places without invitation.")
vn.say("Rue", "Mia? Mia!")
vn.say(None, "I tapped my foot, wait for a very long time (20 seconds) and decided that she must be busy and cancelled this whole thing, so I can just turn around and leave.")
vn.say(None, "I started my bike and about to rode off when a shrill voice caught my attention.")
vn.say("Mia", "WAIT!!! WAIT RUE! I'M SO SORRY I OVERSLEPT WAIIT!!!!!")
vn.say(None, "I rolled my eyes, dammit, she actually woke up.")
vn.say(None, "I turned off my bike and watched as the girl scrambled to open the gates.")
vn.say("Mia", "Please! please, come on in! Make...")
vn.say(None, "The girl gasped, as if she just down 5 flights of stairs.")
vn.say("Mia", "yourself... at home... ha...")
vn.say("Rue", "Thanks, you mind if I park my bike inside?")
vn.say("Mia", "Y-yeah, you can park in the front yard... it's... not used...")
vn.say(None, "I parked the bike and watched as Mia finally managed to catch her breath.")
vn.say("Mia", "Okay, okay, so...")
vn.say(None, "The girl bowed deeply.")
vn.say("Mia", "Thank you so much for visiting me Rue!!!")
vn.say(None, "I sighed.")
vn.say("Rue", "Right, can I go now?")
vn.say("Mia", "NO!")
vn.say(None, "The girl grabbed my arm.")
vn.say("Mia", "Come on, come on, let me show you around the mansion!!!")
vn.say(None, "I followed the girl through the front door and into the mansion.")
vn.say(None, "It's massive, it has long history, and it reeks holy magic. By the devils above I hate this place.")
vn.say("Mia", "And here's the main... Umm... Big room!")
vn.say(None, "I stood in the middle of the grand hall. Large carpeted hallway, pristine and beautiful, with chandeliers glowing above, double door, stained glass, suits of armor. You know, shit people gets paid to draw.")
vn.say(None, "Not that I can afford it.")
vn.say("Mia", "What do you think???")
vn.say("Rue", "Decent")
vn.say("Mia", "Oh you haven't seen the best parts!!!")
vn.say(None, "The girl led me up the grand staircase, walls depicting painting and murals of  old war decorated everything.")
vn.say(None, "God, the embellishments...")
vn.say(None, "Don't read, don't read, don't read...")
vn.say("Rue", "FUCK!")
vn.say("Mia", "What?")
vn.say(None, "The girl froze and turned to me.")
vn.say("Mia", "Wh-what's wrong???")
vn.say("Rue", "Sorry, just... the egregious amount of bullshit depicted in this walls, makes me want to murder you.")
vn.say("Mia", "Me?")
vn.say("Rue", "You're the closest human here...")
vn.say(None, "I pointed at a tapestry.")
vn.say("Rue", "Look... Lucifer didn't "Call Upon The Creatures of Dark to Lay Siege Upon The Light", he was holding an advertising campaign")
vn.say("Mia", "Advertising Campaign?")
vn.say("Rue", "YES!!! He's trying to get more people to go to hell, because with God gone, he can stop torturing people. Hell becomes a business, there's no eternal punishment. It's just a very, very shitty place to live, and he wants to make it a nicer place to live.")
vn.say("Mia", "Whoa... so... if I die and go to hell...")
vn.say("Rue", "You'll get power, a property, depending on your sin. If you're just a fucking normie, you become someone else's property. So it's safer bet to go to heaven.")
vn.say("Mia", "So you should either go all in on Sin or go all in on Virtue, is that it?")
vn.say("Rue", "Bingo!")
vn.say("Mia", "But I thought God decide what's sinful and what virtuous?")
vn.say(None, "We continue walking, talking about heaven and hell.")
vn.say("Rue", "That's the bullcrap, the angels did a counter marketing. They get exterminators to fight of the campaign and Lucifer recruited us, creatures of the dark, to protect the adverts and billboards. We lost, badly, and then the angels ran disiniformation champaign and no one knows how to get a good life in Hell.")
vn.say(None, "I groaned, the memories of a few hundred years ago came to me.")
vn.say("Rue", "Basically, Lucifer operates on certain law. Your sin manifests as power in hell, and like, if you only prey on the weak, then well, you're fucked. Because there's not much 'weakling' in hell, yhear? Serial Killers, Billionaires, and Dictators gets the best out of hell. Pedos, Petty Thief, and Bullies get to be their lackies, you get me???")
vn.say("Mia", "Whoa... I didn't know you're so passionate about this...")
vn.say("Rue", "No, no I don't, I just hate that I have to remember it...")
vn.say(None, "Soon enough we made it to a massive dining room.")
vn.say("Mia", "Here we are! The dining room!")
vn.say(None, "There was a feast atop the table, roasted turkey, steaks, potatoes, vegetables, pasta, and more. It's the kind of feast prepared for a very rich, very powerful people.")
vn.say(None, "...")
vn.say("Rue", "Huh...")
vn.say(None, "I blinked and found traces of house keeping magic, then I glanced at the utensils.")
vn.say("Mia", "It just appeared when I'm not looking, the food I mean...")
vn.say(None, "The girl sat on the dining room.")
vn.say("Mia", "The food will disappear and the dish will clean itself after I finish eating. The fridge is always stocked.")
vn.say("Rue", "Hee...")
vn.say(None, "I sat down facing her on the dining table. I helped myself on the rarest cut of steak.")
vn.say("Mia", "You can come here everyday! We can have breakfast, lunch, and dinner together.")
vn.say(None, "I zoned out of her rambling and took a bite. It's juicy, but still too cooked for my liking.")
vn.say("Rue", "Uhuh...")
vn.say(None, "I chewed slowly, savoring it, wondering if this thing was ever a cow in its past life.")
vn.say("Mia", "Do you like it?")
vn.say("Rue", "Decent")
vn.say("Mia", "Umm... What about the mansion? Do you feel welcome here? Would you like to spend more time in this place?")
vn.say(None, "I looked at her.")
vn.say("Rue", "I'd rather not, let's meet somewhere else")
vn.say("Mia", "Why?")
vn.say("Rue", "This place hates me")
vn.say(None, "I took another bite")
vn.say("Rue", "You can't feel it, but this building wants me gone")
vn.say("Mia", "Hee? Why? It's just a magic building.")
vn.say(None, "I rolled my eyes.")
vn.say("Rue", "Magic requires life as a proxy, all things magical are alive, or...")
vn.say(None, "I narrowed my eyes.")
vn.say("Rue", "Wait, uhh, all things alive are magic, so since this is magic, it's most likely alive.")
vn.say("Mia", "Oooh...")
vn.say(None, "The girl stood up.")
vn.say("Mia", "Mr. Mansion! Please be nice to my new friend!!! She's going to live here with me for as long as I live!")
vn.say(None, "Nothing happens")
vn.say("Rue", "It's not that easy.")
vn.say("Mia", "How do we get rid of the magic?")
vn.say("Rue", "You kill it, but then it'll turn into a regular building and you have to deal with bullshit like chores, cooking, and plumbing.")
vn.say("Mia", "Mmm... What if you... kill it and sell it?")
vn.say("Rue", "What??")
vn.say("Mia", "Yeah! You can, you can kill this mansion, then you can sell it and keep the money! You can use it to do whatever you want.")
vn.say("Rue", "Me? Wait, Mia, shut up, shut up for a moment")
vn.say("Mia", "I mean, it's yours now, I've decided, I don't want this place. Or money. Or anything. Come on, let's kill it...")
vn.say(None, "Killing intent seeps out of the walls and I face palmed.")
vn.say("Rue", "Goddammit you idiot...")
vn.say(None, "A goblet of clear water appeared next to me. Holy water, lethal to vampires like me.")
vn.say("Rue", "I should leave")
vn.say("Mia", "Ah wait, are you sure? Shouldn't we...")
vn.say(None, "I jumped back, dodging a knife flying right at my face.")
vn.say("Rue", "Yeah, apologize to the mansion, and uhh... Remember your neighbor? Mali?")
vn.say("Mia", "Oh? Umm, yes?")
vn.say("Rue", "Go live with him for a bit, this place wants us dead.")
vn.say("Mia", "What do you...")
vn.say(None, "I lunged at her and pulled away just in time as the chandelier dropped right where she was.")
vn.say(None, "CRASH")
vn.say("Rue", "Tch, brace yourself")
vn.say(None, "I carried her bridal style and blitzed through the hallway.")
vn.say(None, "The chandeliers dropped around us. The carpet tried to grab my foot and the suits of armor wave their sword.")
vn.say("Mia", "Aaaaa!")
vn.say(None, "The girl squealed, not scared squeal, but very excited and having the time of her life squeal.")
vn.say("Mia", "It's chasing us! The suits of armor! I knew it can move! Ahahaha!")
vn.say("Rue", "Shut up...")
vn.say(None, "I jumped off the hall way and straight to the main grand hall and blitzed straight at the locked entrance.")
vn.say(None, "Wood splinters and wall cracks as I kicked at the door with all my might. The door exploded outwards revealing the closed off gates.")
vn.say(None, "I ran straight at the gate as numerous thorny vines tried to block us off.")
vn.say(None, "I jumped up in the air, high, as high as I can muster and landed right in front of the mansion entrance.")
vn.say("Mia", "Whoa... Kyah!")
vn.say(None, "I dropped the girl on the ground in front of me.")
vn.say("Rue", "Ugh... Well, at least I don't have to...")
vn.say(None, "I froze.")
vn.say("Rue", "MY BIKE!")
vn.say(None, "I looked back at the mansion, right there, I can see it, my motorbike being swallowed by the earth inside the front yard. There was a certain gentleness in the way my bike was swallowed.")
vn.say(None, "As if the mansion wants me to know that my bike is intact.")
vn.say(None, "I clenched my fist.")
vn.say("Rue", "Your house took my bike hostage.")
vn.say("Mia", "Umm...")
vn.say(None, "I looked at Mia")
vn.say("Choice A", "Let's figure this out, I need my bike back")
vn.say("Choice B", "Kill yourself, I don't want to see you ever again")
vn.say("Choice C", "*punch her in the face and call her out for being an idiot*")
vn.say(None, "---")
