vn.say(None, "I arrived in front of the mansion, it's massive, looks a bit like a castle. So this brat is actually very rich huh?")
vn.say(None, "Hmm... I mean hey, beats the shoebox I live in, new house after she offed herself, good deal I say.")
vn.say("Mia", "Here we are...")
vn.say(None, "The girl was trembling a little as she slowly get off my bike.")
vn.say(None, "Shell gestured at the mansion and forced a cheerful smile.")
vn.say("Mia", "H-here we are!")
vn.say(None, "I raised an eyebrow.")
vn.say("Rue", "Mm, not bad...")
vn.say("Mia", "Would you like to explore?")
vn.say(None, "I head back to my bike.")
vn.say("Rue", "Absolutely not")
vn.say(None, "The girl flinched.")
vn.say("Mia", "H-hey, if you don't get in mansion it doesn't count.")
vn.say(None, "I rolled my eyes.")
vn.say("Rue", "It's 6 AM and I care a lot about my sleep. I'll be back this weekend")
vn.say("Mia", "But... That's just two days!")
vn.say(None, "I paused and looked up. She makes a good point, she wants me to visit her for a week that's seven days.")
vn.say(None, "I'm not gonna cheat her, what am I, the devil?")
vn.say("Rue", "Guess you'll have to stay alive for the next month then")
vn.say("Mia", "Ah, umm, okay, but... But promise me you visit at weekend!")
vn.say("Rue", "Sure... Just don't bother me again at work.")
