vn.say(None, "I arrived in front of the mansion, it's massive, looks a bit like a castle. Yknow, where you'd expect a vampire would live in?")
vn.say("Mia", "We're here!")
vn.say(None, "The girl twirled a little, gesturing at the mansion.")
vn.say("Mia", "This is my home, you can visit anytime!")
vn.say("Rue", "Cool")
vn.say(None, "I gave her a thumbs up and started my motorbike.")
vn.say("Mia", "WAIT!")
vn.say(None, "The girl ran back towards me.")
vn.say("Mia", "You can't just leave! We just got here! At least, at least let me show you my room!")
vn.say("Rue", "It's Thursday 6 AM, I don't want to destroy the only thing I have left in life.")
vn.say(None, "Mia's eyes widened and she stepped closer towards me.")
vn.say("Mia", "The only thing on you have left in life? Wh-what is it? I mean... If you're ready to telll me but...")
vn.say("Rue", "A normal circadian rhythm")
vn.say(None, "Mia paused frozen, then pouted")
vn.say("Mia", "Stop teasing me!")
vn.say(None, "I turned on the engine")
vn.say("Rue", "Wasn't trying to, see ya")
