vn.say(None, "I leaned on to the utility pole, arms folded looking at the hospital building.")
vn.say(None, "It's white... It's sickeningly bright, but thank the devils above it does not have sculpture or statues or other bullshit in it.")
vn.say(None, "Also it doesn't blast me away when I get close.")
vn.say("Mia", "Rue!")
vn.say(None, "The annoying brat waved her hand as she ran up towards me. She's... Fully healed? No sign of injury? No casket?")
vn.say(None, "Huh...")
vn.say("Rue", "Oi, how are you healed so fast?")
vn.say("Mia", "Oh there was a cleric nearby who... Ghuk!")
vn.say(None, "My fist punched her gut on reflex, cutting off her air and sent her on to her knees.")
vn.say("Rue", "Sorry, force of habit")
vn.say(None, "I helped her up.")
vn.say("Rue", "You want a ride home?")
vn.say(None, "The girl gave me a weak smile.")
vn.say("Mia", "Y-yeah, thanks...")
vn.say(None, "---")
vn.say(None, "After a short trek, I finally made it in front of the mansion.")
vn.say(None, "Hmmm... I feel like I recognize this place...")
vn.say(None, "But where???")
vn.say("Mia", "Here we are!")
vn.say(None, "The girl twirled a little as she gestured at the mansion behind her.")
vn.say("Mia", "Home sweet home... Well, kinda, I live here alone see? And the mansion takes care of me!")
vn.say("Rue", "Hee...")
vn.say(None, "I started the engine")
vn.say("Mia", "W-wait! Where are you going?")
vn.say("Rue", "Home")
vn.say("Mia", "WAIT! Wait, wait, wait, don't  just... don't just go! I thought you hate me less now?")
vn.say(None, "I rolled my eyes")
vn.say("Rue", "Look, Mia, as much as I... well, I can't say I want to, but even if I say I will visit you, it's 6 AM, the sun is peeking out, and I don't want to ruin the one thing I have left in the world.")
vn.say("Mia", "The one thing you have left?")
vn.say(None, "The girl stepped closer to me, tentatively.")
vn.say("Mia", "Something... precious?")
vn.say("Rue", "Yes, very precious, very important, very fragile, I took extra care to take care of it.")
vn.say("Mia", "Wh-what is it? I-I mean if you don't want me to pry or... Or... Umm, I mean, if you want to... share?")
vn.say("Rue", "A working circadian cycle, anyway, I'll visit you weekend if I got time")
vn.say(None, "I rode off, the engine drowns out Mia's indignant cries behind me.")
