vn.say(None, "Yet another day in the store. Haa...")
vn.say(None, "I was just finished handling a dwarf asking if the knife sold here is tempered steel and I said no. He bought it either way, saying something about worthy challenge.")
vn.say(None, "The next customer...")
vn.say(None, "Fuck it's her...")
vn.say("Mia", "Oh! You work here?")
vn.say("Rue", "Clearly.")
vn.say("Mia", "Whoa! Okay, okay, umm... I, we haven't got a chance to talk and...")
vn.say("Rue", "You're holding up the line")
vn.say("Mia", "Oh, oh, sorry, I'll, okay, I'll go back when it's less crowded. Hey can I have your number??")
vn.say("Rue", "Not now")
vn.say("Mia", "Right, right...")
vn.say("Rue", "Aren't you going to buy something?")
vn.say("Mia", "Eh? Oh! Uhh... I'll have uhh... this!")
vn.say(None, "She grabbed the chocolate bar on the counter, didn't even bother looking at it.")
vn.say(None, "I scanned the item.")
vn.say("Rue", "That'll be 200 blips")
vn.say("Mia", "Okay, uhh, here...")
vn.say(None, "I process her purchase.")
vn.say("Rue", "Next!")
vn.say(None, "---")
vn.say(None, "It was 11PM, there's no customer... I sighed, getting ready to sit down and idle when the door rings open.")
vn.say("Mia", "Hi again!")
vn.say(None, "I rolled my eyes.")
vn.say("Rue", "Welcome to Pandoramart, how can I help you?")
vn.say("Mia", "Oh! Just buying some... stuff...")
vn.say(None, "The girl walked down the aisle looking for something. She returned with some sticks of candle.")
vn.say(None, "I scanned them without a word.")
vn.say("Rue", "That'll be 150 blips, anything else")
vn.say("Mia", "Wait, wait, wait, uhhh... We haven't had a chance to talk, and look, no line behind me!")
vn.say(None, "Unfortunately...")
vn.say("Rue", "What do  you want?")
vn.say("Mia", "Well, I, I've always been curious, you're a vampire, right? Like the real deal???")
vn.say("Rue", "Yea")
vn.say("Mia", "Do you... drink blood?")
vn.say("Rue", "If I can afford it)"
vn.say("Mia", "Are blood expensive?")
vn.say("Rue", "Humans one yes, very expensive")
vn.say("Mia", "Ummm... Uhh, weird question, but hypothetically... if like, someone offer you their blood, will you...")
vn.say("Rue", "I will refuse, not worth the risk")
vn.say("Mia", "Risk?")
vn.say(None, "I sighed.")
vn.say("Rue", "150 Blips")
vn.say("Mia", "Okay, okay geez... Here,")
vn.say(None, "---")
vn.say(None, "11 PM, and there she is...")
vn.say("Mia", "Hi again!")
vn.say("Rue", "Welcome to Pandoramart, how can I help you?")
vn.say("Mia", "Moo... You're so cold...")
vn.say(None, "The girl walked down the aisle and grabbed a bundle of thick rope.")
vn.say(None, "I scanned the rope.")
vn.say("Rue","That'll be 400 Blips")
vn.say("Mia", "Aren't you going to ask what it's for?")
vn.say("Rue", "400 Blips")
vn.say("Mia", "What if I tell you I'm secretly depressed and I'm gonna hang myself with it?")
vn.say("Rue", "Card or Cash?")
vn.say("Mia", "Ugh... You're impossible... I just want to get to know you!")
vn.say(None, "I sighed and looked around, it's 11 PM, no one is here. She's not holding up the line, and Nyarla is somewhere doing squid / eldritch thing.")
vn.say("Rue", "Fine... Look, I'm not trying to attract attention, that time in alley it was... That's not what I do usually,")
vn.say("Mia", "But you were so cool!")
vn.say("Rue", "What the fuck do you want?")
vn.say("Mia", "Umm, can I have your number? Also, I heard Vampires live for a long time? How old are you? A million years  old? Were you there when dinosaurs walk the land?"")
vn.say(None, "I sighed.")
vn.say("Rue", "I was there during 4th Rapture")
vn.say("Mia", "I KNEW IT!")
vn.say(None, "The girl blurted out, then covered her mouth. She glanced around hastily.")
vn.say("Mia", "I, I mean, that's so cool!")
vn.say(None, "The door bell rings a customer walks in.")
vn.say("Rue", "That's your cue, card or cash,")
vn.say(None, "Mia fumbled through her bag and took out some cash.")
vn.say("Rue", "Thank you for your purchase, have a nice day,")
vn.say(None, "---")
vn.say(None, "It was 5 minutes before 4 AM, the end of my shift.")
vn.say(None, "Hmmm... Something's wrong...")
vn.say(None, "Today was too peaceful...")
vn.say(None, "The door rings open.")
vn.say("Mia", "Hi again!")
vn.say(None, "Nevermind...")
vn.say("Rue", "Make it quick")
vn.say("Mia", "Come on... I thought we had something going on between us!")
vn.say(None, "I blinked, slowly, then turned to Nyarla")
vn.say("Rue", "I'm clocking out")
vn.say("Nyarla", "Etadru oyht iwnu fevah!")
vn.say(None, "I stepped out of the pandoramart with the annoying girl clinging on to me.")
vn.say("Mia", "Ne, ne, Rue, why do you work here? In this uhh... Convenience store?")
vn.say("Rue", "Cuz job market is bullshit")
vn.say("Mia", "Uhh... is it?")
vn.say("Rue", "Do you work? Go to school?")
vn.say("Mia", "No...")
vn.say(None, "Mia averted her gaze and looked down.")
vn.say("Mia", "I live alone, in a big mansion... I... I lied, Mikalio isn't my big bro, he's just... a neighbor. I had him pretend that...")
vn.say("Rue", "I know, it's obvious")
vn.say("Mia", "Eh?")
vn.say("Rue", "Mm, anything else?")
vn.say("Mia", "W-well, I live alone and... If possible I'd like you to... Keep me company? Sometime? This is umm... an invitation see? To the mansion?")
vn.say("Rue", "I'll think about it.")
vn.say("Mia", "Rue... Do you hate me? Is there anything I can do to make you... not hate me?")
vn.say("Choice A", "I don't hate you")
vn.say("Choice B", "Nothing, I want you gone")
vn.say("Choice C", "Yes, I want to hurt you")
